### PR TITLE
Fix/fileread before sending more changes

### PR DESCRIPTION
**Pull request by arybkin**
Contains fix from https://github.com/reportportal/agent-net-vstest/pull/30. + Additional changes for log requests sending. 

Added additional helper, that prepare log requests list for RP. Just for splitting logic and for making ReportPortalLogger class less weight.

### CODE REVIEW

**Comment by nvborisenko** [comment]
Please leave only one PR to fix it.

Let's rework it little bit. I see the behaviour of agent as following: each time when agent reads file content, agent puts warning message to the server in case of unsuccessful attempt. So message would be "{user-message}\n{exception-message}". Where user-message is a message from user, exception-message is descriptive message why agent was not able to read file.

**Comment by arybkin** [comment]
Hey, I updated due to your comments. Please check when will be ready (not on vacation=)

**Review by nvborisenko — CHANGES_REQUESTED** [review]
This is not clear why agent should make several attempts to read file content. The original issue is in something who is locking this file. I agree that reporting should not be broken if file is locked, but agent should just leave a message why he couldn't read file. This is simple and clear.

**Comment by arybkin** [comment]
Ok. removed this logic

**Comment by nvborisenko** [comment]
@arybkin thank you.

**Pull request merged**
